../verifyta -o1 -u verification1-avoid.xml > results/avoid1.txt
../verifyta -o1 -u verification1-reach.xml > results/reach1.txt
../verifyta -o1 -u verification2-avoid.xml > results/avoid2.txt
../verifyta -o1 -u verification2-reach.xml > results/reach2.txt
../verifyta -o1 -u verification3-avoid-phase1.xml > results/avoid3-1.txt
../verifyta -o1 -u verification3-avoid-phase2.xml > results/avoid3-2.txt
../verifyta -o1 -u verification3-avoid-phase3.xml > results/avoid3-3.txt
../verifyta -o1 -u verification3-reach-phase1.xml > results/reach3-1.txt
../verifyta -o1 -u verification3-reach-phase2.xml > results/reach3-2.txt
../verifyta -o1 -u verification3-reach-phase3.xml > results/reach3-3.txt
../verifyta -o1 -u verification4-avoid.xml > results/avoid4.txt
../verifyta -o1 -u verification4-reach.xml > results/reach4.txt
../verifyta -o1 -u verification5-avoid.xml > results/avoid5.txt
../verifyta -o1 -u verification5-reach.xml > results/reach5.txt
